version: "3.8"

services:
  qdrant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__STORAGE__PATH: "/qdrant/storage"

volumes:
  qdrant_data:
    driver: local
